# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'design.ui'
##
## Created by: Qt User Interface Compiler version 6.7.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QDoubleSpinBox, QGroupBox,
    QHeaderView, QLabel, QLineEdit, QMainWindow,
    QPushButton, QSizePolicy, QStackedWidget, QTableWidget,
    QTableWidgetItem, QTextEdit, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(640, 470)
        MainWindow.setMinimumSize(QSize(640, 470))
        MainWindow.setMaximumSize(QSize(640, 470))
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.stackedWidget = QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(0, 0, 640, 470))
        self.transaction_page = QWidget()
        self.transaction_page.setObjectName(u"transaction_page")
        self.back_to_MainMenu_bt = QPushButton(self.transaction_page)
        self.back_to_MainMenu_bt.setObjectName(u"back_to_MainMenu_bt")
        self.back_to_MainMenu_bt.setGeometry(QRect(10, 10, 80, 30))
        self.filter_label = QLabel(self.transaction_page)
        self.filter_label.setObjectName(u"filter_label")
        self.filter_label.setGeometry(QRect(135, 10, 60, 30))
        self.filter_categories_comboBox = QComboBox(self.transaction_page)
        self.filter_categories_comboBox.setObjectName(u"filter_categories_comboBox")
        self.filter_categories_comboBox.setGeometry(QRect(200, 15, 130, 20))
        self.filter_date_comboBox = QComboBox(self.transaction_page)
        self.filter_date_comboBox.setObjectName(u"filter_date_comboBox")
        self.filter_date_comboBox.setGeometry(QRect(335, 15, 150, 20))
        self.filter_type_comboBox = QComboBox(self.transaction_page)
        self.filter_type_comboBox.setObjectName(u"filter_type_comboBox")
        self.filter_type_comboBox.setGeometry(QRect(490, 15, 130, 20))
        self.delete_trans_bt = QPushButton(self.transaction_page)
        self.delete_trans_bt.setObjectName(u"delete_trans_bt")
        self.delete_trans_bt.setGeometry(QRect(480, 60, 145, 24))
        self.sort_label = QLabel(self.transaction_page)
        self.sort_label.setObjectName(u"sort_label")
        self.sort_label.setGeometry(QRect(14, 62, 131, 16))
        self.sort_comboBox = QComboBox(self.transaction_page)
        self.sort_comboBox.addItem("")
        self.sort_comboBox.addItem("")
        self.sort_comboBox.setObjectName(u"sort_comboBox")
        self.sort_comboBox.setGeometry(QRect(140, 60, 111, 22))
        self.tableWidget = QTableWidget(self.transaction_page)
        self.tableWidget.setObjectName(u"tableWidget")
        self.tableWidget.setGeometry(QRect(10, 100, 620, 360))
        self.stackedWidget.addWidget(self.transaction_page)
        self.main_page = QWidget()
        self.main_page.setObjectName(u"main_page")
        self.groupBox_2 = QGroupBox(self.main_page)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(325, 10, 310, 250))
        self.balance_label = QLabel(self.groupBox_2)
        self.balance_label.setObjectName(u"balance_label")
        self.balance_label.setGeometry(QRect(0, 0, 310, 55))
        self.residue_label = QLabel(self.groupBox_2)
        self.residue_label.setObjectName(u"residue_label")
        self.residue_label.setGeometry(QRect(10, 55, 89, 55))
        self.income_label = QLabel(self.groupBox_2)
        self.income_label.setObjectName(u"income_label")
        self.income_label.setGeometry(QRect(10, 110, 89, 55))
        self.outcome_label = QLabel(self.groupBox_2)
        self.outcome_label.setObjectName(u"outcome_label")
        self.outcome_label.setGeometry(QRect(10, 165, 89, 55))
        self.balance_value_label = QLabel(self.groupBox_2)
        self.balance_value_label.setObjectName(u"balance_value_label")
        self.balance_value_label.setGeometry(QRect(110, 55, 141, 55))
        self.income_value_label = QLabel(self.groupBox_2)
        self.income_value_label.setObjectName(u"income_value_label")
        self.income_value_label.setGeometry(QRect(110, 110, 141, 55))
        self.outcome_value_label = QLabel(self.groupBox_2)
        self.outcome_value_label.setObjectName(u"outcome_value_label")
        self.outcome_value_label.setGeometry(QRect(110, 165, 141, 55))
        self.groupBox = QGroupBox(self.main_page)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 10, 310, 450))
        self.price_label = QLabel(self.groupBox)
        self.price_label.setObjectName(u"price_label")
        self.price_label.setGeometry(QRect(10, 110, 89, 55))
        self.price_doubleSpinBox = QDoubleSpinBox(self.groupBox)
        self.price_doubleSpinBox.setObjectName(u"price_doubleSpinBox")
        self.price_doubleSpinBox.setGeometry(QRect(110, 127, 185, 21))
        self.price_doubleSpinBox.setMaximum(1000000000.000000000000000)
        self.categoty_label = QLabel(self.groupBox)
        self.categoty_label.setObjectName(u"categoty_label")
        self.categoty_label.setGeometry(QRect(10, 220, 89, 55))
        self.category_comboBox = QComboBox(self.groupBox)
        self.category_comboBox.setObjectName(u"category_comboBox")
        self.category_comboBox.setGeometry(QRect(110, 237, 185, 21))
        self.product_name_label = QLabel(self.groupBox)
        self.product_name_label.setObjectName(u"product_name_label")
        self.product_name_label.setGeometry(QRect(10, 55, 89, 55))
        self.product_name_lineEdit = QLineEdit(self.groupBox)
        self.product_name_lineEdit.setObjectName(u"product_name_lineEdit")
        self.product_name_lineEdit.setGeometry(QRect(110, 72, 185, 21))
        self.product_label = QLabel(self.groupBox)
        self.product_label.setObjectName(u"product_label")
        self.product_label.setGeometry(QRect(0, 0, 310, 55))
        self.comment_label = QLabel(self.groupBox)
        self.comment_label.setObjectName(u"comment_label")
        self.comment_label.setGeometry(QRect(10, 330, 89, 80))
        self.comment_textEdit = QTextEdit(self.groupBox)
        self.comment_textEdit.setObjectName(u"comment_textEdit")
        self.comment_textEdit.setGeometry(QRect(110, 343, 181, 61))
        self.commit_trans_bt = QPushButton(self.groupBox)
        self.commit_trans_bt.setObjectName(u"commit_trans_bt")
        self.commit_trans_bt.setGeometry(QRect(10, 415, 285, 25))
        self.type_label = QLabel(self.groupBox)
        self.type_label.setObjectName(u"type_label")
        self.type_label.setGeometry(QRect(10, 165, 89, 55))
        self.type_comboBox = QComboBox(self.groupBox)
        self.type_comboBox.setObjectName(u"type_comboBox")
        self.type_comboBox.setGeometry(QRect(110, 182, 185, 21))
        self.date_label = QLabel(self.groupBox)
        self.date_label.setObjectName(u"date_label")
        self.date_label.setGeometry(QRect(10, 275, 89, 55))
        self.date_comboBox = QComboBox(self.groupBox)
        self.date_comboBox.setObjectName(u"date_comboBox")
        self.date_comboBox.setGeometry(QRect(110, 292, 185, 21))
        self.transactions_bt = QPushButton(self.main_page)
        self.transactions_bt.setObjectName(u"transactions_bt")
        self.transactions_bt.setGeometry(QRect(325, 265, 152, 195))
        self.delete_category_bt = QPushButton(self.main_page)
        self.delete_category_bt.setObjectName(u"delete_category_bt")
        self.delete_category_bt.setGeometry(QRect(483, 265, 152, 95))
        self.new_category_bt = QPushButton(self.main_page)
        self.new_category_bt.setObjectName(u"new_category_bt")
        self.new_category_bt.setGeometry(QRect(483, 365, 152, 95))
        self.stackedWidget.addWidget(self.main_page)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.stackedWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"\u0423\u0447\u0435\u0442 \u0441\u043e\u0431\u0441\u0442\u0432\u0435\u043d\u043d\u044b\u0445 \u0434\u0435\u043d\u0435\u0436\u043d\u044b\u0445 \u0441\u0440\u0435\u0434\u0441\u0442\u0432", None))
        self.back_to_MainMenu_bt.setText(QCoreApplication.translate("MainWindow", u"\u041d\u0430\u0437\u0430\u0434", None))
        self.filter_label.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:10pt;\">\u0424\u0418\u041b\u042c\u0422\u0420:</span></p></body></html>", None))
        self.delete_trans_bt.setText(QCoreApplication.translate("MainWindow", u"\u0423\u0434\u0430\u043b\u0438\u0442\u044c \u0442\u0440\u0430\u043d\u0437\u0430\u043a\u0446\u0438\u044e", None))
        self.sort_label.setText(QCoreApplication.translate("MainWindow", u"\u0421\u043e\u0440\u0442\u0438\u0440\u043e\u0432\u0430\u0442\u044c \u043f\u043e \u0446\u0435\u043d\u0435:", None))
        self.sort_comboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"\u043e\u0442 min \u043a max", None))
        self.sort_comboBox.setItemText(1, QCoreApplication.translate("MainWindow", u"\u043e\u0442 min \u043a max", None))

        self.groupBox_2.setTitle("")
#if QT_CONFIG(tooltip)
        self.balance_label.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><br/></p></body></html>", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.balance_label.setWhatsThis(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><br/></p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.balance_label.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\">\u0411\u0410\u041b\u0410\u041d\u0421 \u0417\u0410 \u041c\u0415\u0421\u042f\u0426</p></body></html>", None))
        self.residue_label.setText(QCoreApplication.translate("MainWindow", u"\u0411\u0430\u043b\u0430\u043d\u0441:", None))
        self.income_label.setText(QCoreApplication.translate("MainWindow", u"\u0414\u043e\u0445\u043e\u0434\u044b:", None))
        self.outcome_label.setText(QCoreApplication.translate("MainWindow", u"\u0420\u0430\u0441\u0445\u043e\u0434\u044b:", None))
        self.balance_value_label.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:12pt;\">1000000000.00</span></p></body></html>", None))
        self.income_value_label.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:12pt;\">1000000000.00</span></p></body></html>", None))
        self.outcome_value_label.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:12pt;\">1000000000.00</span></p></body></html>", None))
        self.groupBox.setTitle("")
        self.price_label.setText(QCoreApplication.translate("MainWindow", u"\u0426\u0435\u043d\u0430:", None))
        self.categoty_label.setText(QCoreApplication.translate("MainWindow", u"\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f:", None))
        self.product_name_label.setText(QCoreApplication.translate("MainWindow", u"\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435:", None))
#if QT_CONFIG(tooltip)
        self.product_label.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><br/></p></body></html>", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.product_label.setWhatsThis(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><br/></p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.product_label.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\">\u041d\u043e\u0432\u0430\u044f \u0442\u0440\u0430\u043d\u0437\u0430\u043a\u0446\u0438\u044f</p></body></html>", None))
        self.comment_label.setText(QCoreApplication.translate("MainWindow", u"\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439:", None))
        self.commit_trans_bt.setText(QCoreApplication.translate("MainWindow", u"\u041f\u043e\u0434\u0442\u0432\u0435\u0440\u0434\u0438\u0442\u044c", None))
        self.type_label.setText(QCoreApplication.translate("MainWindow", u"\u0422\u0438\u043f:", None))
        self.date_label.setText(QCoreApplication.translate("MainWindow", u"\u0414\u0430\u0442\u0430:", None))
        self.transactions_bt.setText(QCoreApplication.translate("MainWindow", u"\u0422\u0420\u0410\u041d\u0417\u0410\u041a\u0426\u0418\u0418", None))
        self.delete_category_bt.setText(QCoreApplication.translate("MainWindow", u"\u0423\u0414\u0410\u041b\u0418\u0422\u042c \u041a\u0410\u0422\u0415\u0413\u041e\u0420\u0418\u042e", None))
        self.new_category_bt.setText(QCoreApplication.translate("MainWindow", u"\u041d\u041e\u0412\u0410\u042f \u041a\u0410\u0422\u0415\u0413\u041e\u0420\u0418\u042f", None))
    # retranslateUi

